[dependencies]
flox = ">=0.11.0,<0.12"
numpy = ">=1.22"
python = "3.12.*"
xarray = ">=2023.1"
xclim = ">=0.59.1"
xsdba = ">=0.5,<0.6"

[environments]
dev = ["dev"]
docs = ["docs"]

[feature.dev.dependencies]
black = "*"
cdsapi = ">=0.7.7,<0.8"
fire = "*"
ipykernel = "*"
ipython = "*"
mypy = "*"
nbformat = ">=5.10.4,<6"
pre-commit = "*"
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
pytest-xdist = "*"
ruff = "*"

[feature.dev.pypi-dependencies]
earthkit-transforms = ">=0.5.3.1, <0.6"

[feature.docs.dependencies]
furo = "*"
nbsphinx = ">=0.9.8,<0.10"
pandoc = "*"
sphinx = "*"
sphinx-autoapi = ">=3.6.1,<4"
sphinx-rtd-theme = ">=3.0.2,<4"

[feature.docs.tasks]
docs-build = "rm -rf docs/_build && sphinx-build -M html docs docs/_build"

[pypi-dependencies]
earthkit-climate = {path = ".", editable = true}
earthkit-data = ">=0.17.0"
earthkit-plots = ">=0.5.0,<0.6"

[tasks]
qa = "pre-commit run --all-files"
template-update = "pre-commit run --all-files cruft -c .pre-commit-config-cruft.yaml"
test = "python -m pytest"
test-integration = "python -m pytest tests/integration -m integration"
type-check = "python -m mypy . --no-namespace-packages"

[workspace]
channels = ["conda-forge"]
name = "earthkit-climate"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
