[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=65", "setuptools-scm>=8", "wheel"]

[project]
authors = [
  {name = "European Centre for Medium-Range Weather Forecasts (ECMWF)", email = "software.support@ecmwf.int"}
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering"
]
dependencies = [
  "earthkit-data>=1.0rc0",
  "earthkit-utils>=1.0rc0",
  "flox>=0.11",
  "numpy>=1.22",
  "xarray>=2023.1",
  "xclim>=0.59.1,<1",
  "xsdba>=0.5,<0.6"
]
description = "Tools for calculating climate indicies, climate change analysis and attribution."
dynamic = ["readme", "version"]
license = {file = "LICENSE"}
name = "earthkit-climate"
requires-python = ">=3.11"
# Sample data source plugin for earthkit-data
entry-points."earthkit.data.sources".earthkit-climate-sample = "earthkit.climate.sample_source:SampleSource"

[project.optional-dependencies]
dev = [
  "earthkit-climate[docs,docs-notebooks,test,test-benchmark]",
  "pre-commit"
]
docs = [
  "furo",
  "nbsphinx",
  "roman-numerals-py>=3.1,<4",
  "sphinx",
  "sphinx-autoapi",
  "sphinx_design"
]
docs-notebooks = [
  "cdsapi",
  "ipykernel",
  "ipython",
  "earthkit-plots>=1.0rc0",
  "earthkit-transforms>=1.0rc0"
]
test = [
  "pytest",
  "pytest-cov",
  "pytest-mock",
  "pytest-xdist"
]
test-benchmark = [
  "earthkit-climate[test]",
  "fire",
  "matplotlib",
  "seaborn",
  "pandas",
  "tqdm",
  "psutil"
]

[tool.coverage.run]
branch = true
source = ["src/earthkit/climate"]

[tool.pytest.ini_options]
addopts = "-vv --cov --cov-report=html --doctest-glob='*.md' --doctest-glob='*.rst' -m 'not integration' -n auto"
markers = [
  "integration: marks tests as slow integration tests (skipped by default)"
]
testpaths = ["tests/unit"]

[tool.ruff]
line-length = 120
preview = true
lint.ignore = [
  "D1",  # pydocstyle: Missing Docstrings
  "D107",  # pydocstyle: numpy convention
  "D203",
  "D205",
  "D212",
  "D213",
  "D401",
  "D402",
  "D413",
  "D415",
  "D416",
  "D417"
]
lint.select = [
  "D",  # pydocstyle
  "E",  # pycodestyle
  "F",  # pyflakes
  "I",  # isort
  "W"  # pycodestyle warnings
]
lint.per-file-ignores."docs/conf.py" = [
  "E501"  # line too long
]

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}

# ---- Namespace package configuration ----
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "src/earthkit/climate/version.py"
write_to_template = '''
# Do not change! Do not track in version control!
__version__ = "{version}"
'''
