# SPDX-FileCopyrightText: 2025 European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0

# This file is automatically generated. Do not edit by hand.

from typing import Any

import xarray as xr
import xclim.indicators.seaIce
from earthkit.data import FieldList
from earthkit.utils.decorators import format_handler

# from earthkit.climate.utils.decorators import metadata_handler


@format_handler()
# @metadata_handler(xclim.indicators.seaIce.sea_ice_area)
def sea_ice_area(
    siconc: xr.DataArray | FieldList | str = "siconc",
    areacello: xr.DataArray | FieldList | str = "areacello",
    ds: xr.Dataset | None = None,
    *,
    thresh: str | float | int | xr.DataArray | FieldList = "15 %",
    **kwargs: Any,
) -> xr.DataArray | FieldList:
    """
    Sea ice area.

    A measure of total ocean surface covered by sea ice.

    **Units:**

    - sea_ice_area: m2

    This function wraps `xclim.indicators.seaIce.sea_ice_area <https://xclim.readthedocs.io/en/stable/api_indicators.html#xclim.indicators.seaIce.sea_ice_area>`_.

    Parameters
    ----------
    siconc : xarray.DataArray | earthkit.data.FieldList | str
        Sea ice concentration (area fraction).
    areacello : xarray.DataArray | earthkit.data.FieldList | str
        Grid cell area (usually over the ocean).
    thresh : str | float | int | xarray.DataArray | earthkit.data.FieldList
        Minimum sea ice concentration for a grid cell to contribute to the sea ice extent.
    ds : xarray.Dataset | None
        Input dataset.
    **kwargs : Any
        Additional keyword arguments.

    Returns
    -------
    xarray.DataArray | earthkit.data.FieldList
        The computed index.
    """
    return xclim.indicators.seaIce.sea_ice_area(
        siconc=siconc,
        areacello=areacello,
        thresh=thresh,
        ds=ds,
        **kwargs,
    )


@format_handler()
# @metadata_handler(xclim.indicators.seaIce.sea_ice_extent)
def sea_ice_extent(
    siconc: xr.DataArray | FieldList | str = "siconc",
    areacello: xr.DataArray | FieldList | str = "areacello",
    ds: xr.Dataset | None = None,
    *,
    thresh: str | float | int | xr.DataArray | FieldList = "15 %",
    **kwargs: Any,
) -> xr.DataArray | FieldList:
    """
    Sea ice extent.

    A measure of the extent of all areas where sea ice concentration exceeds a threshold.

    **Units:**

    - sea_ice_extent: m2

    This function wraps `xclim.indicators.seaIce.sea_ice_extent <https://xclim.readthedocs.io/en/stable/api_indicators.html#xclim.indicators.seaIce.sea_ice_extent>`_.

    Parameters
    ----------
    siconc : xarray.DataArray | earthkit.data.FieldList | str
        Sea ice concentration (area fraction).
    areacello : xarray.DataArray | earthkit.data.FieldList | str
        Grid cell area.
    thresh : str | float | int | xarray.DataArray | earthkit.data.FieldList
        Minimum sea ice concentration for a grid cell to contribute to the sea ice extent.
    ds : xarray.Dataset | None
        Input dataset.
    **kwargs : Any
        Additional keyword arguments.

    Returns
    -------
    xarray.DataArray | earthkit.data.FieldList
        The computed index.
    """
    return xclim.indicators.seaIce.sea_ice_extent(
        siconc=siconc,
        areacello=areacello,
        thresh=thresh,
        ds=ds,
        **kwargs,
    )
