# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0

name: test-cd
on:
  pull_request:
    branches: ["main"]
jobs:
  pypi:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi.yml@v2
    secrets: inherit
    with:
      testpypi: true
